const fs = require("fs");
let c = fs.readFileSync("app.js", "utf8");
c = c.replace(/\\B/g, "\B");
c = c.replace(/\\d/g, "\d");
c = c.replace(/\\b(?![rn])/g, "\b");
c = c.replace(/\u0007/g, "\u2022");
c = c.replace(/\?\?/g, "\uD83D\uDC4B");
c = c.replace(/\r\r/g, "\r");
fs.writeFileSync("app.js", c, "utf8");
console.log("Fixed, length:", c.length);